apiVersion: v1
kind: ServiceAccount
metadata:
  name: idle-svc
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: idle-svc
  namespace: monitoring
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get", "list"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: idle-svc
  namespace: monitoring
subjects:
  - kind: ServiceAccount
    name: idle-svc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: idle-svc 